CREATE TABLE "LAMP_NONE"."BASE_EMPLOYEE"
(
"ID" BIGINT NOT NULL,
"IS_DEFAULT" BIT DEFAULT 0 NOT NULL,
"POSITION_ID" BIGINT,
"USER_ID" BIGINT NOT NULL,
"LAST_COMPANY_ID" BIGINT,
"LAST_DEPT_ID" BIGINT,
"REAL_NAME" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"ACTIVE_STATUS" CHAR(2 CHAR) DEFAULT '20',
"POSITION_STATUS" CHAR(2 CHAR) DEFAULT '10',
"STATE" BIT DEFAULT 1,
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_EMP_USER_ID" UNIQUE("USER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.BASE_EMPLOYEE IS '员工';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."ACTIVE_STATUS" IS '激活状态;[10-未激活 20-已激活]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Global.ACTIVE_STATUS)';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."IS_DEFAULT" IS '是否默认员工;[0-否 1-是]';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."LAST_COMPANY_ID" IS '上一次登录单位ID';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."LAST_DEPT_ID" IS '上一次登录部门ID';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."POSITION_ID" IS '所属岗位';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."POSITION_STATUS" IS '职位状态;[10-在职 20-离职]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.POSITION_STATUS)';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."REAL_NAME" IS '真实姓名';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."STATE" IS '状态;[0-禁用 1-启用]';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."UPDATED_TIME" IS '最后更新时间';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE."USER_ID" IS '用户';


CREATE TABLE "LAMP_NONE"."BASE_EMPLOYEE_ORG_REL"
(
"ID" BIGINT NOT NULL,
"ORG_ID" BIGINT NOT NULL,
"EMPLOYEE_ID" BIGINT NOT NULL,
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_EMPLOYEE_ORG" UNIQUE("ORG_ID", "EMPLOYEE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.BASE_EMPLOYEE_ORG_REL IS '员工所在部门';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ORG_REL."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ORG_REL."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ORG_REL."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ORG_REL."EMPLOYEE_ID" IS '关联员工';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ORG_REL."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ORG_REL."ORG_ID" IS '关联机构';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ORG_REL."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ORG_REL."UPDATED_TIME" IS '最后更新时间';


CREATE TABLE "LAMP_NONE"."BASE_EMPLOYEE_ROLE_REL"
(
"ID" BIGINT NOT NULL,
"ROLE_ID" BIGINT NOT NULL,
"EMPLOYEE_ID" BIGINT NOT NULL,
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_ERR_ROLE_EMPLOYEE" UNIQUE("ROLE_ID", "EMPLOYEE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.BASE_EMPLOYEE_ROLE_REL IS '员工的角色';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ROLE_REL."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ROLE_REL."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ROLE_REL."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ROLE_REL."EMPLOYEE_ID" IS '所属员工;#base_employee';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ROLE_REL."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ROLE_REL."ROLE_ID" IS '拥有角色;#base_role';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ROLE_REL."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN LAMP_NONE.BASE_EMPLOYEE_ROLE_REL."UPDATED_TIME" IS '最后更新时间';


CREATE TABLE "LAMP_NONE"."BASE_OPERATION_LOG"
(
"ID" BIGINT NOT NULL,
"REQUEST_IP" VARCHAR(50 CHAR) DEFAULT '',
"TYPE" VARCHAR(5 CHAR) DEFAULT 'OPT',
"USER_NAME" VARCHAR(50 CHAR) DEFAULT '',
"DESCRIPTION" VARCHAR(255 CHAR) DEFAULT '',
"CLASS_PATH" VARCHAR(255 CHAR) DEFAULT '',
"ACTION_METHOD" VARCHAR(50 CHAR) DEFAULT '',
"REQUEST_URI" VARCHAR(500 CHAR) DEFAULT '',
"HTTP_METHOD" VARCHAR(10 CHAR) DEFAULT 'GET',
"START_TIME" TIMESTAMP(0),
"FINISH_TIME" TIMESTAMP(0),
"CONSUMING_TIME" BIGINT DEFAULT 0,
"UA" VARCHAR(500 CHAR) DEFAULT '',
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.BASE_OPERATION_LOG IS '操作日志';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."ACTION_METHOD" IS '请求方法';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."CLASS_PATH" IS '类路径';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."CONSUMING_TIME" IS '消耗时间';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."DESCRIPTION" IS '操作描述';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."FINISH_TIME" IS '完成时间';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."HTTP_METHOD" IS '请求类型;#HttpMethod{GET:GET请求;POST:POST请求;PUT:PUT请求;DELETE:DELETE请求;PATCH:PATCH请求;TRACE:TRACE请求;HEAD:HEAD请求;OPTIONS:OPTIONS请求;}';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."ID" IS '主键';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."REQUEST_IP" IS '操作IP';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."REQUEST_URI" IS '请求地址';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."START_TIME" IS '开始时间';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."TYPE" IS '日志类型;#LogType{OPT:操作类型;EX:异常类型}';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."UA" IS '浏览器';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."UPDATED_TIME" IS '最后更新时间';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG."USER_NAME" IS '操作人';


CREATE TABLE "LAMP_NONE"."BASE_OPERATION_LOG_EXT"
(
"ID" BIGINT NOT NULL,
"PARAMS" CLOB,
"RESULT" CLOB,
"EX_DETAIL" CLOB,
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.BASE_OPERATION_LOG_EXT IS '操作日志扩展';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG_EXT."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG_EXT."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG_EXT."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG_EXT."EX_DETAIL" IS '异常描述';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG_EXT."ID" IS '主键';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG_EXT."PARAMS" IS '请求参数';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG_EXT."RESULT" IS '返回值';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG_EXT."UPDATED_BY" IS '最后更新人ID';
COMMENT ON COLUMN LAMP_NONE.BASE_OPERATION_LOG_EXT."UPDATED_TIME" IS '最后更新时间';


CREATE TABLE "LAMP_NONE"."BASE_ORG"
(
"ID" BIGINT NOT NULL,
"NAME" VARCHAR(255 CHAR) NOT NULL,
"TYPE_" CHAR(2 CHAR) DEFAULT '10',
"SHORT_NAME" VARCHAR(255 CHAR),
"PARENT_ID" BIGINT,
"TREE_GRADE" INT DEFAULT 0,
"TREE_PATH" VARCHAR(255 CHAR),
"SORT_VALUE" INT DEFAULT 1,
"STATE" BIT DEFAULT 1,
"REMARKS" VARCHAR(255 CHAR),
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_ORG_NAME" UNIQUE("NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.BASE_ORG IS '组织';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."NAME" IS '名称';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."PARENT_ID" IS '父组织';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."REMARKS" IS '备注';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."SHORT_NAME" IS '简称';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."SORT_VALUE" IS '排序';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."STATE" IS '状态;[0-禁用 1-启用]';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."TREE_GRADE" IS '树层级';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."TREE_PATH" IS '树路径;用id拼接树结构';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."TYPE_" IS '类型;[10-单位 20-部门]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.ORG_TYPE)';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."UPDATED_BY" IS '修改人';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG."UPDATED_TIME" IS '修改时间';


CREATE TABLE "LAMP_NONE"."BASE_ORG_ROLE_REL"
(
"ID" BIGINT NOT NULL,
"ORG_ID" BIGINT NOT NULL,
"ROLE_ID" BIGINT NOT NULL,
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_ORG_ROLE" UNIQUE("ORG_ID", "ROLE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.BASE_ORG_ROLE_REL IS '组织的角色';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG_ROLE_REL."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG_ROLE_REL."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG_ROLE_REL."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG_ROLE_REL."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG_ROLE_REL."ORG_ID" IS '所属部门;#base_org';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG_ROLE_REL."ROLE_ID" IS '拥有角色;#base_role';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG_ROLE_REL."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN LAMP_NONE.BASE_ORG_ROLE_REL."UPDATED_TIME" IS '最后更新时间';


CREATE TABLE "LAMP_NONE"."BASE_POSITION"
(
"ID" BIGINT NOT NULL,
"NAME" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"ORG_ID" BIGINT,
"STATE" BIT DEFAULT 1,
"REMARKS" VARCHAR(255 CHAR) DEFAULT '',
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_NAME" UNIQUE("NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.BASE_POSITION IS '岗位';
COMMENT ON COLUMN LAMP_NONE.BASE_POSITION."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.BASE_POSITION."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN LAMP_NONE.BASE_POSITION."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.BASE_POSITION."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.BASE_POSITION."NAME" IS '名称';
COMMENT ON COLUMN LAMP_NONE.BASE_POSITION."ORG_ID" IS '所属组织;#base_org@Echo(api = EchoApi.ORG_ID_CLASS)';
COMMENT ON COLUMN LAMP_NONE.BASE_POSITION."REMARKS" IS '备注';
COMMENT ON COLUMN LAMP_NONE.BASE_POSITION."STATE" IS '状态;0-禁用 1-启用';
COMMENT ON COLUMN LAMP_NONE.BASE_POSITION."UPDATED_BY" IS '修改人';
COMMENT ON COLUMN LAMP_NONE.BASE_POSITION."UPDATED_TIME" IS '修改时间';


CREATE TABLE "LAMP_NONE"."BASE_ROLE"
(
"ID" BIGINT NOT NULL,
"CATEGORY" CHAR(2 CHAR) DEFAULT '10' NOT NULL,
"TYPE_" CHAR(2 CHAR) DEFAULT '20' NOT NULL,
"NAME" VARCHAR(50 CHAR) NOT NULL,
"CODE" VARCHAR(20 CHAR) NOT NULL,
"REMARKS" VARCHAR(255 CHAR),
"STATE" BIT DEFAULT 1,
"READONLY_" BIT DEFAULT 0,
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_CODE" UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.BASE_ROLE IS '角色';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE."CATEGORY" IS '角色类别;[10-功能角色 20-桌面角色 30-数据角色]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.ROLE_CATEGORY)';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE."CODE" IS '编码';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE."NAME" IS '名称';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE."READONLY_" IS '内置角色';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE."REMARKS" IS '备注';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE."STATE" IS '状态';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE."TYPE_" IS '角色类型;[10-系统角色 20-自定义角色]; 
@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Global.DATA_TYPE)';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE."UPDATED_BY" IS '更新人';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE."UPDATED_TIME" IS '更新时间';


CREATE TABLE "LAMP_NONE"."BASE_ROLE_RESOURCE_REL"
(
"ID" BIGINT NOT NULL,
"RESOURCE_ID" BIGINT NOT NULL,
"APPLICATION_ID" BIGINT NOT NULL,
"ROLE_ID" BIGINT NOT NULL,
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_ROLE_RESOURCE" UNIQUE("RESOURCE_ID", "ROLE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.BASE_ROLE_RESOURCE_REL IS '角色的资源';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE_RESOURCE_REL."APPLICATION_ID" IS '所属应用;#def_application';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE_RESOURCE_REL."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE_RESOURCE_REL."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE_RESOURCE_REL."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE_RESOURCE_REL."ID" IS '主键';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE_RESOURCE_REL."RESOURCE_ID" IS '拥有资源;#def_resource';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE_RESOURCE_REL."ROLE_ID" IS '所属角色;#base_role';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE_RESOURCE_REL."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN LAMP_NONE.BASE_ROLE_RESOURCE_REL."UPDATED_TIME" IS '最后更新时间';


CREATE TABLE "LAMP_NONE"."COM_APPENDIX"
(
"ID" BIGINT NOT NULL,
"BIZ_ID" BIGINT NOT NULL,
"BIZ_TYPE" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"CREATED_TIME" TIMESTAMP(0) NOT NULL,
"CREATED_BY" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.COM_APPENDIX IS '业务附件';
COMMENT ON COLUMN LAMP_NONE.COM_APPENDIX."BIZ_ID" IS '业务id';
COMMENT ON COLUMN LAMP_NONE.COM_APPENDIX."BIZ_TYPE" IS '业务类型;同一个业务，不同的字段，需要分别设置不同的业务类型';
COMMENT ON COLUMN LAMP_NONE.COM_APPENDIX."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.COM_APPENDIX."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.COM_APPENDIX."ID" IS '文件ID';


CREATE TABLE "LAMP_NONE"."COM_FILE"
(
"ID" BIGINT NOT NULL,
"BIZ_TYPE" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"FILE_TYPE" VARCHAR(10 CHAR) DEFAULT 'OTHER',
"STORAGE_TYPE" VARCHAR(30 CHAR) DEFAULT 'LOCAL',
"BUCKET" VARCHAR(255 CHAR) DEFAULT '',
"PATH" VARCHAR(255 CHAR) DEFAULT '',
"URL" VARCHAR(255 CHAR) DEFAULT '',
"UNIQUE_FILE_NAME" VARCHAR(255 CHAR) DEFAULT '',
"FILE_MD5" VARCHAR(255 CHAR) DEFAULT '',
"ORIGINAL_FILE_NAME" VARCHAR(255 CHAR) DEFAULT '',
"CONTENT_TYPE" VARCHAR(255 CHAR) DEFAULT '',
"SUFFIX" VARCHAR(255 CHAR) DEFAULT '',
"SIZE_" BIGINT DEFAULT 0,
"CREATED_TIME" TIMESTAMP(0) NOT NULL,
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0) NOT NULL,
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.COM_FILE IS '增量文件上传日志';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."BIZ_TYPE" IS '业务类型;同一个业务，不同的字段，需要分别设置不同的业务类型';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."BUCKET" IS '桶';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."CONTENT_TYPE" IS '文件类型';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."FILE_MD5" IS '文件md5';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."FILE_TYPE" IS '文件类型;#FileType{IMAGE:图片;VIDEO:视频;AUDIO:音频;DOC:文档;OTHER:其他;}';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."ORIGINAL_FILE_NAME" IS '原始文件名';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."PATH" IS '文件相对地址';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."SIZE_" IS '大小';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."STORAGE_TYPE" IS '存储类型;#FileStorageType{LOCAL:本地;FAST_DFS:FastDFS;MIN_IO:MinIO;ALI_OSS:阿里云OSS;QINIU_OSS:七牛云OSS;HUAWEI_OSS:华为云OSS;}';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."SUFFIX" IS '后缀';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."UNIQUE_FILE_NAME" IS '唯一文件名';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."UPDATED_BY" IS '最后修改人';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."UPDATED_TIME" IS '最后修改时间';
COMMENT ON COLUMN LAMP_NONE.COM_FILE."URL" IS '文件访问地址';


CREATE TABLE "LAMP_NONE"."DEF_APPLICATION"
(
"ID" BIGINT NOT NULL,
"APP_KEY" VARCHAR(255 CHAR) DEFAULT '',
"APP_SECRET" VARCHAR(255 CHAR) DEFAULT '',
"NAME" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"VERSION" VARCHAR(255 CHAR) DEFAULT '',
"TYPE" CHAR(2 CHAR) DEFAULT '10' NOT NULL,
"REDIRECT" VARCHAR(255 CHAR),
"INTRODUCE" VARCHAR(255 CHAR) DEFAULT '',
"REMARK" VARCHAR(255 CHAR) DEFAULT '',
"URL" VARCHAR(255 CHAR) DEFAULT '',
"IS_GENERAL" BIT DEFAULT 0,
"IS_VISIBLE" BIT DEFAULT 1,
"SORT_VALUE" INT DEFAULT 1,
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_APPLICATION_KEY" UNIQUE("APP_KEY")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_APPLICATION IS '应用';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."APP_KEY" IS '应用标识';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."APP_SECRET" IS '应用秘钥';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."INTRODUCE" IS '简介';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."IS_GENERAL" IS '是否公共应用;0-否 1-是';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."IS_VISIBLE" IS '是否可见;0-否 1-是';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."NAME" IS '应用名称';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."REDIRECT" IS '重定向地址';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."REMARK" IS '备注';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."SORT_VALUE" IS '排序';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."TYPE" IS '应用类型;[10-自建应用 20-第三方应用]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.System.APPLICATION_TYPE)';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."UPDATED_TIME" IS '最后更新时间';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."URL" IS '应用地址';
COMMENT ON COLUMN LAMP_NONE.DEF_APPLICATION."VERSION" IS '版本';


CREATE TABLE "LAMP_NONE"."DEF_AREA"
(
"ID" BIGINT NOT NULL,
"CODE" VARCHAR(64 CHAR) DEFAULT '' NOT NULL,
"DIVISION_CODE" VARCHAR(255 CHAR) DEFAULT '',
"NAME" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"FULL_NAME" VARCHAR(255 CHAR) DEFAULT '',
"SORT_VALUE" INT DEFAULT 1,
"LONGITUDE" VARCHAR(255 CHAR) DEFAULT '',
"LATITUDE" VARCHAR(255 CHAR) DEFAULT '',
"LEVEL_" CHAR(2 CHAR) DEFAULT '10',
"SOURCE_" CHAR(2 CHAR) DEFAULT '',
"STATE" BIT DEFAULT 0,
"TREE_GRADE" INT DEFAULT 0,
"TREE_PATH" VARCHAR(512 CHAR) DEFAULT '/',
"PARENT_ID" BIGINT,
"CREATED_TIME" TIMESTAMP(0) NOT NULL,
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0) NOT NULL,
"UPDATED_BY" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_AREA_CODE" UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_AREA IS '地区表';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."CODE" IS '编码;统计用区划代码';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."DIVISION_CODE" IS '城乡划分代码';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."FULL_NAME" IS '全名';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."ID" IS 'id';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."LATITUDE" IS '维度';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."LEVEL_" IS '行政级别;[10-国家 20-省份/直辖市 30-地市 40-区县 50-乡镇]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Global.AREA_LEVEL)';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."LONGITUDE" IS '经度';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."NAME" IS '名称';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."PARENT_ID" IS '父ID';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."SORT_VALUE" IS '排序';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."SOURCE_" IS '数据来源;[10-爬取 20-新增]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.System.AREA_SOURCE)';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."STATE" IS '状态';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."TREE_GRADE" IS '树层级';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."TREE_PATH" IS '树路径';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."UPDATED_BY" IS '更新人';
COMMENT ON COLUMN LAMP_NONE.DEF_AREA."UPDATED_TIME" IS '更新时间';


CREATE TABLE "LAMP_NONE"."DEF_CLIENT"
(
"ID" BIGINT NOT NULL,
"CLIENT_ID" VARCHAR(24 CHAR) DEFAULT '' NOT NULL,
"CLIENT_SECRET" VARCHAR(32 CHAR) DEFAULT '' NOT NULL,
"NAME" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"TYPE" CHAR(2 CHAR) DEFAULT '10',
"REMARKS" VARCHAR(255 CHAR) DEFAULT '',
"STATE" BIT DEFAULT 1,
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_CLIENT_CLIENT_ID" UNIQUE("CLIENT_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_CLIENT IS '客户端';
COMMENT ON COLUMN LAMP_NONE.DEF_CLIENT."CLIENT_ID" IS '客户端ID';
COMMENT ON COLUMN LAMP_NONE.DEF_CLIENT."CLIENT_SECRET" IS '客户端密码';
COMMENT ON COLUMN LAMP_NONE.DEF_CLIENT."CREATED_BY" IS '创建人id';
COMMENT ON COLUMN LAMP_NONE.DEF_CLIENT."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_CLIENT."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.DEF_CLIENT."NAME" IS '客户端名称';
COMMENT ON COLUMN LAMP_NONE.DEF_CLIENT."REMARKS" IS '备注';
COMMENT ON COLUMN LAMP_NONE.DEF_CLIENT."STATE" IS '状态';
COMMENT ON COLUMN LAMP_NONE.DEF_CLIENT."TYPE" IS '类型;[10-WEB网站;15-移动端应用;20-手机H5网页;25-内部服务; 30-第三方应用]
@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.System.CLIENT_TYPE)';
COMMENT ON COLUMN LAMP_NONE.DEF_CLIENT."UPDATED_BY" IS '更新人id';
COMMENT ON COLUMN LAMP_NONE.DEF_CLIENT."UPDATED_TIME" IS '更新时间';


CREATE TABLE "LAMP_NONE"."DEF_DATASOURCE_CONFIG"
(
"ID" BIGINT NOT NULL,
"NAME" VARCHAR(255 CHAR) NOT NULL,
"USERNAME" VARCHAR(255 CHAR) NOT NULL,
"PASSWORD" VARCHAR(255 CHAR) NOT NULL,
"URL" VARCHAR(255 CHAR) NOT NULL,
"DRIVER_CLASS_NAME" VARCHAR(255 CHAR) NOT NULL,
"CREATED_TIME" TIMESTAMP(0) NOT NULL,
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0) NOT NULL,
"UPDATED_BY" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_DATASOURCE_CONFIG IS '数据源';
COMMENT ON COLUMN LAMP_NONE.DEF_DATASOURCE_CONFIG."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.DEF_DATASOURCE_CONFIG."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_DATASOURCE_CONFIG."DRIVER_CLASS_NAME" IS '驱动';
COMMENT ON COLUMN LAMP_NONE.DEF_DATASOURCE_CONFIG."ID" IS '主键ID';
COMMENT ON COLUMN LAMP_NONE.DEF_DATASOURCE_CONFIG."NAME" IS '名称';
COMMENT ON COLUMN LAMP_NONE.DEF_DATASOURCE_CONFIG."PASSWORD" IS '密码';
COMMENT ON COLUMN LAMP_NONE.DEF_DATASOURCE_CONFIG."UPDATED_BY" IS '修改人';
COMMENT ON COLUMN LAMP_NONE.DEF_DATASOURCE_CONFIG."UPDATED_TIME" IS '修改时间';
COMMENT ON COLUMN LAMP_NONE.DEF_DATASOURCE_CONFIG."URL" IS '链接';
COMMENT ON COLUMN LAMP_NONE.DEF_DATASOURCE_CONFIG."USERNAME" IS '账号';


CREATE TABLE "LAMP_NONE"."DEF_DICT"
(
"ID" BIGINT NOT NULL,
"PARENT_ID" BIGINT DEFAULT 0 NOT NULL,
"PARENT_KEY" VARCHAR(255 CHAR),
"CLASSIFY" CHAR(2 CHAR) DEFAULT '20' NOT NULL,
"KEY_" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"NAME" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"STATE" BIT DEFAULT 1,
"REMARK" VARCHAR(255 CHAR) DEFAULT '',
"SORT_VALUE" INT DEFAULT 1,
"ICON" VARCHAR(255 CHAR) DEFAULT '',
"CSS_STYLE" VARCHAR(255 CHAR) DEFAULT '',
"CSS_CLASS" VARCHAR(255 CHAR) DEFAULT '',
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0) NOT NULL,
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0) NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_DICT_KEY" UNIQUE("PARENT_ID", "KEY_")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_DICT IS '字典';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."CLASSIFY" IS '分类;[10-系统字典 20-业务字典]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.System.DICT_CLASSIFY)';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."CREATED_BY" IS '创建人id';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."CSS_CLASS" IS 'css类元素';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."CSS_STYLE" IS 'css样式';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."ICON" IS '图标';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."KEY_" IS '标识';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."NAME" IS '名称';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."PARENT_ID" IS '字典ID';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."PARENT_KEY" IS '父字典标识';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."REMARK" IS '备注';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."SORT_VALUE" IS '排序';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."STATE" IS '状态';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."UPDATED_BY" IS '更新人id';
COMMENT ON COLUMN LAMP_NONE.DEF_DICT."UPDATED_TIME" IS '更新时间';


CREATE TABLE "LAMP_NONE"."DEF_GEN_TABLE"
(
"ID" BIGINT NOT NULL,
"NAME" VARCHAR(200 CHAR) NOT NULL,
"COMMENT_" VARCHAR(500 CHAR),
"SWAGGER_COMMENT" VARCHAR(255 CHAR),
"DS_ID" BIGINT NOT NULL,
"AUTHOR" VARCHAR(255 CHAR) NOT NULL,
"SUB_ID" BIGINT,
"SUB_JAVA_FIELD_NAME" VARCHAR(255 CHAR),
"ENTITY_NAME" VARCHAR(255 CHAR) NOT NULL,
"ENTITY_SUPER_CLASS" CHAR(2 CHAR) NOT NULL,
"SUPER_CLASS" CHAR(2 CHAR) NOT NULL,
"PARENT" VARCHAR(255 CHAR) NOT NULL,
"PLUS_APPLICATION_NAME" VARCHAR(255 CHAR),
"PLUS_MODULE_NAME" VARCHAR(255 CHAR),
"SERVICE_NAME" VARCHAR(255 CHAR),
"MODULE_NAME" VARCHAR(255 CHAR),
"CHILD_PACKAGE_NAME" VARCHAR(255 CHAR),
"IS_TENANT_LINE" BIT DEFAULT 0 NOT NULL,
"DS_VALUE" VARCHAR(255 CHAR),
"IS_DS" BIT DEFAULT 0 NOT NULL,
"IS_LOMBOK" BIT DEFAULT 1 NOT NULL,
"IS_CHAIN" BIT DEFAULT 1 NOT NULL,
"IS_COLUMN_CONSTANT" BIT DEFAULT 0 NOT NULL,
"GEN_TYPE" CHAR(2 CHAR) DEFAULT '01' NOT NULL,
"OUTPUT_DIR" VARCHAR(255 CHAR) DEFAULT '/',
"FRONT_OUTPUT_DIR" VARCHAR(255 CHAR),
"FRONT_SOY_OUTPUT_DIR" VARCHAR(255 CHAR),
"FRONT_VBEN5_OUTPUT_DIR" VARCHAR(255 CHAR),
"TPL_TYPE" CHAR(2 CHAR) DEFAULT '01' NOT NULL,
"POPUP_TYPE" CHAR(2 CHAR) DEFAULT '01' NOT NULL,
"ADD_AUTH" VARCHAR(255 CHAR),
"EDIT_AUTH" VARCHAR(255 CHAR),
"DELETE_AUTH" VARCHAR(255 CHAR),
"VIEW_AUTH" VARCHAR(255 CHAR),
"COPY_AUTH" VARCHAR(255 CHAR),
"ADD_SHOW" BIT DEFAULT 1 NOT NULL,
"EDIT_SHOW" BIT DEFAULT 1 NOT NULL,
"DELETE_SHOW" BIT DEFAULT 1 NOT NULL,
"COPY_SHOW" BIT DEFAULT 1 NOT NULL,
"VIEW_SHOW" BIT DEFAULT 1 NOT NULL,
"OPTIONS" VARCHAR(1000 CHAR),
"REMARK" VARCHAR(500 CHAR),
"MENU_PARENT_ID" BIGINT,
"MENU_APPLICATION_ID" BIGINT,
"MENU_NAME" VARCHAR(255 CHAR),
"MENU_ICON" VARCHAR(255 CHAR),
"TREE_PARENT_ID" BIGINT,
"TREE_NAME" VARCHAR(255 CHAR),
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0) NOT NULL,
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0) NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_GEN_TABLE IS '代码生成';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."ADD_AUTH" IS '新增按钮权限编码';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."ADD_SHOW" IS '新增按钮是否显示';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."AUTHOR" IS '作者';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."CHILD_PACKAGE_NAME" IS '子包名';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."COMMENT_" IS '表描述';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."COPY_AUTH" IS '复制按钮权限编码';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."COPY_SHOW" IS '复制按钮是否显示';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."CREATED_BY" IS '创建者';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."DELETE_AUTH" IS '删除按钮权限编码';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."DELETE_SHOW" IS '删除按钮是否显示';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."DS_ID" IS '数据源';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."DS_VALUE" IS '数据源';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."EDIT_AUTH" IS '编辑按钮权限编码';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."EDIT_SHOW" IS '编辑按钮是否显示';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."ENTITY_NAME" IS '实体类名称';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."ENTITY_SUPER_CLASS" IS '实体父类;
#EntitySuperClassEnum{SUPER_ENTITY:01}';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."FRONT_OUTPUT_DIR" IS '前端(Vben)生成路径;（不填默认项目路径）';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."FRONT_SOY_OUTPUT_DIR" IS '前端(Soybean)生成路径;（不填默认项目路径）';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."FRONT_VBEN5_OUTPUT_DIR" IS '前端生成路径';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."GEN_TYPE" IS '生成代码方式;、; [01-zip压缩包 02-自定义路径]
#GenTypeEnum{GEN:01,直接生成;ZIP:02,打包下载;}';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."ID" IS '编号';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."IS_CHAIN" IS '是否为链式模型';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."IS_COLUMN_CONSTANT" IS '是否生成字段常量';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."IS_DS" IS '数据源级租户注解';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."IS_LOMBOK" IS '是否为lombok模型';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."IS_TENANT_LINE" IS '行级租户注解';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."MENU_APPLICATION_ID" IS '所属应用ID';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."MENU_ICON" IS '菜单图标';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."MENU_NAME" IS '菜单名称';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."MENU_PARENT_ID" IS '上级菜单ID';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."MODULE_NAME" IS '模块名';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."NAME" IS '表名称';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."OPTIONS" IS '其它生成选项';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."OUTPUT_DIR" IS '生成路径;（不填默认项目路径）';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."PARENT" IS '基础包路径';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."PLUS_APPLICATION_NAME" IS '前端应用名;如：src/views目录下的basic和devOperation,basic表示基础平台。devOperation表示开发运营系统。xxx 表示你们自己新建的xxx系统。';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."PLUS_MODULE_NAME" IS '前端模块名;如：src/views/devOperation目录下的文件夹名
如：src/views/basic 目录下的文件夹名';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."POPUP_TYPE" IS '弹窗方式; #PopupTypeEnum{MODAL:01,对话框;DRAWER:02,抽屉;}';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."REMARK" IS '备注';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."SERVICE_NAME" IS '服务名';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."SUB_ID" IS '关联子表的ID';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."SUB_JAVA_FIELD_NAME" IS '子表关联的外键Java字段名';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."SUPER_CLASS" IS '父类;

#SuperClassEnum{SUPER_CLASS:01}';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."SWAGGER_COMMENT" IS 'swagger描述';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."TPL_TYPE" IS '使用的模板; #TplEnum{SIMPLE:01,单表;TREE:02,树结构;MAIN_SUB:03,主从结构}';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."TREE_NAME" IS '名称字段名';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."TREE_PARENT_ID" IS '父ID字段名';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."UPDATED_BY" IS '更新者';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."UPDATED_TIME" IS '更新时间';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."VIEW_AUTH" IS '查看按钮权限编码';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE."VIEW_SHOW" IS '详情按钮是否显示';


CREATE TABLE "LAMP_NONE"."DEF_GEN_TABLE_COLUMN"
(
"ID" BIGINT NOT NULL,
"TABLE_ID" BIGINT NOT NULL,
"NAME" VARCHAR(255 CHAR) NOT NULL,
"COMMENT_" VARCHAR(512 CHAR),
"SWAGGER_COMMENT" VARCHAR(255 CHAR),
"TYPE" VARCHAR(255 CHAR) NOT NULL,
"JAVA_TYPE" VARCHAR(512 CHAR) NOT NULL,
"JAVA_FIELD" VARCHAR(255 CHAR) NOT NULL,
"TS_TYPE" VARCHAR(255 CHAR) NOT NULL,
"SIZE_" BIGINT DEFAULT 0 NOT NULL,
"DIGIT" INT DEFAULT 0,
"IS_PK" BIT DEFAULT 0 NOT NULL,
"IS_INCREMENT" BIT DEFAULT 0 NOT NULL,
"IS_REQUIRED" BIT DEFAULT 0 NOT NULL,
"IS_LOGIC_DELETE_FIELD" BIT DEFAULT 0 NOT NULL,
"IS_VERSION_FIELD" BIT DEFAULT 0 NOT NULL,
"FILL" VARCHAR(255 CHAR),
"IS_EDIT" BIT DEFAULT 1 NOT NULL,
"IS_LIST" BIT DEFAULT 1 NOT NULL,
"IS_QUERY" BIT DEFAULT 0 NOT NULL,
"WIDTH" VARCHAR(255 CHAR),
"QUERY_TYPE" VARCHAR(255 CHAR) DEFAULT '03',
"COMPONENT" VARCHAR(255 CHAR),
"SOY_COMPONENT" VARCHAR(255 CHAR),
"VXE_COMPONENT" VARCHAR(255 CHAR),
"DICT_TYPE" VARCHAR(255 CHAR),
"ECHO_STR" VARCHAR(255 CHAR),
"ENUM_STR" VARCHAR(255 CHAR),
"SORT_VALUE" INT DEFAULT 0,
"EDIT_DEF_VALUE" VARCHAR(255 CHAR),
"EDIT_HELP_MESSAGE" VARCHAR(255 CHAR),
"INDEX_HELP_MESSAGE" VARCHAR(255 CHAR),
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_GEN_TABLE_COLUMN IS '代码生成字段';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."COMMENT_" IS '列描述';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."COMPONENT" IS 'Vben组件;（文本框、文本域、下拉框、复选框、单选框、日期控件）';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."CREATED_BY" IS '创建者';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."DICT_TYPE" IS '字典类型';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."DIGIT" IS '小数位数';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."ECHO_STR" IS 'Echo';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."EDIT_DEF_VALUE" IS '默认值';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."EDIT_HELP_MESSAGE" IS '提示信息';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."ENUM_STR" IS '枚举';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."FILL" IS '填充类型;
#FieldFill{INSERT:1}';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."INDEX_HELP_MESSAGE" IS '列表提示信息';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."IS_EDIT" IS '编辑';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."IS_INCREMENT" IS '自增';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."IS_LIST" IS '列表';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."IS_LOGIC_DELETE_FIELD" IS '逻辑删除';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."IS_PK" IS '主键';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."IS_QUERY" IS '查询';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."IS_REQUIRED" IS '必填';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."IS_VERSION_FIELD" IS '乐观锁';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."JAVA_FIELD" IS 'JAVA字段名';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."JAVA_TYPE" IS 'JAVA类型';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."NAME" IS '列名称';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."QUERY_TYPE" IS '查询方式;
#SqlConditionEnum{EQUAL:01}
（等于、不等于、大于、小于、范围）';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."SIZE_" IS '长度';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."SORT_VALUE" IS '排序';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."SOY_COMPONENT" IS 'Soybean组件';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."SWAGGER_COMMENT" IS '文档描述';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."TABLE_ID" IS '所属表ID';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."TS_TYPE" IS 'TS类型';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."TYPE" IS '列类型';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."UPDATED_BY" IS '更新者';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."UPDATED_TIME" IS '更新时间';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."VXE_COMPONENT" IS 'Vxe组件;（文本框、文本域、下拉框、复选框、单选框、日期控件）';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TABLE_COLUMN."WIDTH" IS '宽度';


CREATE TABLE "LAMP_NONE"."DEF_GEN_TEST_SIMPLE"
(
"ID" BIGINT NOT NULL,
"NAME" VARCHAR(24 CHAR) DEFAULT '大法师' NOT NULL,
"PARENT_ID" BIGINT,
"SORT_VALUE" INT DEFAULT 22,
"STOCK" INT NOT NULL,
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT DEFAULT 123123,
"TYPE_" TEXT,
"TYPE2" CLOB,
"TYPE3" VARCHAR(255 CHAR),
"STATE" BIT DEFAULT 0,
"TEST4" INT,
"TEST5" DATE,
"TEST6" TIMESTAMP(0),
"LABEL" VARCHAR(255 CHAR),
"TEST7" CHAR(10 CHAR) DEFAULT '01',
"TEST12" INT,
"USER_ID" BIGINT,
"ORG_ID" BIGINT,
"TEST8" DECIMAL(16,4) DEFAULT 21.23,
"TEST9" REAL,
"TEST10" DECIMAL(24,6),
"TEST11" DECIMAL(2,0),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_GEN_TEST_SIMPLE IS '测试树结构';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."LABEL" IS '名称';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."NAME" IS '名称';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."ORG_ID" IS '组织;@Echo(api = EchoApi.ORG_ID_CLASS)';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."PARENT_ID" IS '父id';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."SORT_VALUE" IS '排序';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."STATE" IS '状态';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."STOCK" IS '库存';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."TEST10" IS '浮点';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."TEST11" IS 'xiao树';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."TEST12" IS '整形字典;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Global.TEST_ADD_DICT)[1-测试 2-新增 aad-haha]';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."TEST4" IS '测试';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."TEST5" IS '时间';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."TEST6" IS '日期';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."TEST7" IS '字符字典;@Echo(api = "top.tangyh.lamp.common.api.DictApi", dictType="GLOBAL_SEX")';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."TEST8" IS '小数';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."TEST9" IS '浮点2';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."TYPE2" IS '商品类型2;;
#{ordinary:01,普通;gift:02,赠品;}';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."TYPE3" IS '学历;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS,  dictType = EchoDictType.Global.EDUCATION)';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."TYPE_" IS '商品类型;;
#ProductType{ordinary:普通;gift:赠品}';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."UPDATED_BY" IS '修改人';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."UPDATED_TIME" IS '修改时间';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_SIMPLE."USER_ID" IS '用户;@Echo(api = EchoApi.POSITION_ID_CLASS)';


CREATE TABLE "LAMP_NONE"."DEF_GEN_TEST_TREE"
(
"ID" BIGINT NOT NULL,
"NAME" VARCHAR(24 CHAR) DEFAULT '大法师' NOT NULL,
"PARENT_ID" BIGINT,
"SORT_VALUE" INT DEFAULT 22,
"STOCK" INT NOT NULL,
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT DEFAULT 123123,
"TYPE_" TEXT,
"TYPE2" CLOB,
"TYPE3" VARCHAR(255 CHAR),
"STATE" BIT DEFAULT 0,
"TEST4" INT,
"TEST5" DATE,
"TEST6" TIMESTAMP(0),
"LABEL" VARCHAR(255 CHAR),
"TEST7" CHAR(10 CHAR) DEFAULT '01',
"TEST12" INT,
"USER_ID" BIGINT,
"ORG_ID" BIGINT,
"TEST8" DECIMAL(16,4) DEFAULT 21.23,
"TEST9" REAL,
"TEST10" DECIMAL(24,6),
"TEST11" DECIMAL(2,0),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_GEN_TEST_TREE IS '测试树结构';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."LABEL" IS '名称';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."NAME" IS '名称';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."ORG_ID" IS '组织;@Echo(api = EchoApi.ORG_ID_CLASS)';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."PARENT_ID" IS '父id';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."SORT_VALUE" IS '排序';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."STATE" IS '状态';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."STOCK" IS '库存';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."TEST10" IS '浮点';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."TEST11" IS 'xiao树';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."TEST12" IS '整形字典;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Global.TEST_ADD_DICT)[1-测试 2-新增 aad-haha]';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."TEST4" IS '测试';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."TEST5" IS '时间';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."TEST6" IS '日期';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."TEST7" IS '字符字典;@Echo(api = "top.tangyh.lamp.common.api.DictApi", dictType="GLOBAL_SEX")';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."TEST8" IS '小数';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."TEST9" IS '浮点2';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."TYPE2" IS '商品类型2;#{ordinary:01,普通;gift:02,赠品;}';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."TYPE3" IS '学历;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS,  dictType = EchoDictType.Global.EDUCATION)';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."TYPE_" IS '商品类型;
#ProductType{ordinary:普通;gift:赠品}';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."UPDATED_BY" IS '修改人';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."UPDATED_TIME" IS '修改时间';
COMMENT ON COLUMN LAMP_NONE.DEF_GEN_TEST_TREE."USER_ID" IS '用户;@Echo(api = EchoApi.POSITION_ID_CLASS)[1-aa 2-ddd]';


CREATE TABLE "LAMP_NONE"."DEF_INTERFACE"
(
"ID" BIGINT NOT NULL,
"CODE" VARCHAR(255 CHAR) NOT NULL,
"NAME" VARCHAR(255 CHAR) NOT NULL,
"EXEC_MODE" CHAR(2 CHAR) DEFAULT '01',
"SCRIPT" TEXT,
"IMPL_CLASS" VARCHAR(255 CHAR),
"STATE" BIT DEFAULT 1,
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_INTERFACE_CODE" UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_INTERFACE IS '接口';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE."CODE" IS '接口编码';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE."EXEC_MODE" IS '执行方式;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.INTERFACE_EXEC_MODE)[01-实现类 02-脚本]';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE."IMPL_CLASS" IS '实现类';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE."NAME" IS '接口名称';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE."SCRIPT" IS '实现脚本';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE."STATE" IS '状态';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE."UPDATED_BY" IS '修改人';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE."UPDATED_TIME" IS '修改时间';


CREATE TABLE "LAMP_NONE"."DEF_INTERFACE_PROPERTY"
(
"ID" BIGINT NOT NULL,
"INTERFACE_ID" BIGINT NOT NULL,
"NAME" VARCHAR(255 CHAR) NOT NULL,
"KEY_" VARCHAR(255 CHAR) NOT NULL,
"VALUE" VARCHAR(255 CHAR) NOT NULL,
"SORT_VALUE" INT DEFAULT 0,
"REMARKS" VARCHAR(255 CHAR),
"CREATED_TIME" TIMESTAMP(0) NOT NULL,
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0) NOT NULL,
"UPDATED_BY" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_I_P_INTERFACE_ID_KEY" UNIQUE("INTERFACE_ID", "KEY_")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_INTERFACE_PROPERTY IS '接口属性';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE_PROPERTY."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE_PROPERTY."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE_PROPERTY."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE_PROPERTY."INTERFACE_ID" IS '接口ID';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE_PROPERTY."KEY_" IS '参数键';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE_PROPERTY."NAME" IS '参数名称';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE_PROPERTY."REMARKS" IS '备注';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE_PROPERTY."SORT_VALUE" IS '顺序号';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE_PROPERTY."UPDATED_BY" IS '修改人';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE_PROPERTY."UPDATED_TIME" IS '修改时间';
COMMENT ON COLUMN LAMP_NONE.DEF_INTERFACE_PROPERTY."VALUE" IS '参数值';


CREATE TABLE "LAMP_NONE"."DEF_LOGIN_LOG"
(
"ID" BIGINT NOT NULL,
"TENANT_ID" BIGINT,
"EMPLOYEE_ID" BIGINT,
"USER_ID" BIGINT,
"REQUEST_IP" VARCHAR(50 CHAR) DEFAULT '',
"NICK_NAME" VARCHAR(255 CHAR) DEFAULT '',
"USERNAME" VARCHAR(255 CHAR) DEFAULT '',
"STATUS" CHAR(2 CHAR) DEFAULT '01',
"DESCRIPTION" VARCHAR(255 CHAR) DEFAULT '',
"LOGIN_DATE" CHAR(10 CHAR),
"UA" VARCHAR(512 CHAR) DEFAULT '',
"BROWSER" VARCHAR(255 CHAR) DEFAULT '',
"BROWSER_VERSION" VARCHAR(255 CHAR) DEFAULT '',
"OPERATING_SYSTEM" VARCHAR(255 CHAR) DEFAULT '',
"LOCATION" VARCHAR(50 CHAR) DEFAULT '',
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_LOGIN_LOG IS '登录日志';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."BROWSER" IS '浏览器名称';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."BROWSER_VERSION" IS '浏览器版本';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."DESCRIPTION" IS '登录描述';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."EMPLOYEE_ID" IS '登录员工';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."ID" IS '主键';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."LOCATION" IS '登录地点';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."LOGIN_DATE" IS '登录时间';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."NICK_NAME" IS '登录人姓名';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."OPERATING_SYSTEM" IS '操作系统';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."REQUEST_IP" IS '登录IP';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."STATUS" IS '登录状态;[01-登录成功 02-验证码错误 03-密码错误 04-账号锁定]
    @Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.System.LOGIN_STATUS)';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."TENANT_ID" IS '所属企业';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."UA" IS '浏览器请求头';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."UPDATED_TIME" IS '最后更新时间';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."USER_ID" IS '登录用户';
COMMENT ON COLUMN LAMP_NONE.DEF_LOGIN_LOG."USERNAME" IS '登录人账号';


CREATE TABLE "LAMP_NONE"."DEF_MSG_TEMPLATE"
(
"ID" BIGINT NOT NULL,
"INTERFACE_ID" VARCHAR(255 CHAR) NOT NULL,
"TYPE" CHAR(2 CHAR) NOT NULL,
"CODE" VARCHAR(255 CHAR) NOT NULL,
"NAME" VARCHAR(255 CHAR),
"STATE" BIT,
"TEMPLATE_CODE" VARCHAR(255 CHAR),
"SIGN" VARCHAR(255 CHAR),
"TITLE" VARCHAR(255 CHAR),
"CONTENT" CLOB NOT NULL,
"SCRIPT" VARCHAR(255 CHAR),
"PARAM" VARCHAR(255 CHAR),
"REMARKS" VARCHAR(255 CHAR),
"TARGET_" CHAR(2 CHAR),
"AUTO_READ" BIT DEFAULT 1,
"REMIND_MODE" CHAR(2 CHAR),
"URL" VARCHAR(255 CHAR),
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_MSG_TEMPLATE_CODE" UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_MSG_TEMPLATE IS '消息模板';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."AUTO_READ" IS '自动已读';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."CODE" IS '模板标识';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."CONTENT" IS '模板内容';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."CREATED_BY" IS '创建人ID';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."ID" IS '模板ID';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."INTERFACE_ID" IS '接口ID';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."NAME" IS '模板名称';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."PARAM" IS '模板参数';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."REMARKS" IS '备注';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."REMIND_MODE" IS '提醒方式;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.NOTICE_REMIND_MODE)[01-待办 02-预警 03-提醒]';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."SCRIPT" IS '脚本';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."SIGN" IS '签名';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."STATE" IS '状态';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."TARGET_" IS '打开方式;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.NOTICE_TARGET)[01-页面 02-弹窗 03-新开窗口]';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."TEMPLATE_CODE" IS '模板编码';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."TITLE" IS '标题';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."TYPE" IS '消息类型;[01-短信 02-邮件 03-站内信];@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.MSG_TEMPLATE_TYPE)';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."UPDATED_BY" IS '最后修改人';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."UPDATED_TIME" IS '最后修改时间';
COMMENT ON COLUMN LAMP_NONE.DEF_MSG_TEMPLATE."URL" IS '跳转地址';


CREATE TABLE "LAMP_NONE"."DEF_PARAMETER"
(
"ID" BIGINT NOT NULL,
"KEY_" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"VALUE" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"NAME" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"REMARKS" VARCHAR(255 CHAR) DEFAULT '',
"STATE" BIT DEFAULT 1,
"PARAM_TYPE" CHAR(2 CHAR) DEFAULT '20',
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0) NOT NULL,
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0) NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_PARAM_KEY" UNIQUE("KEY_")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_PARAMETER IS '参数配置';
COMMENT ON COLUMN LAMP_NONE.DEF_PARAMETER."CREATED_BY" IS '创建人id';
COMMENT ON COLUMN LAMP_NONE.DEF_PARAMETER."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_PARAMETER."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.DEF_PARAMETER."KEY_" IS '参数键';
COMMENT ON COLUMN LAMP_NONE.DEF_PARAMETER."NAME" IS '参数名称';
COMMENT ON COLUMN LAMP_NONE.DEF_PARAMETER."PARAM_TYPE" IS '类型;[10-系统参数 20-业务参数]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.System.PARAMETER_TYPE)';
COMMENT ON COLUMN LAMP_NONE.DEF_PARAMETER."REMARKS" IS '备注';
COMMENT ON COLUMN LAMP_NONE.DEF_PARAMETER."STATE" IS '状态';
COMMENT ON COLUMN LAMP_NONE.DEF_PARAMETER."UPDATED_BY" IS '更新人id';
COMMENT ON COLUMN LAMP_NONE.DEF_PARAMETER."UPDATED_TIME" IS '更新时间';
COMMENT ON COLUMN LAMP_NONE.DEF_PARAMETER."VALUE" IS '参数值';


CREATE TABLE "LAMP_NONE"."DEF_RESOURCE"
(
"ID" BIGINT NOT NULL,
"APPLICATION_ID" BIGINT NOT NULL,
"CODE" VARCHAR(255 CHAR) NOT NULL,
"NAME" VARCHAR(255 CHAR) NOT NULL,
"RESOURCE_TYPE" CHAR(2 CHAR) DEFAULT '20' NOT NULL,
"PARENT_ID" BIGINT NOT NULL,
"OPEN_WITH" CHAR(2 CHAR) DEFAULT '01',
"DESCRIBE_" VARCHAR(255 CHAR) DEFAULT '',
"PATH" VARCHAR(255 CHAR) DEFAULT '',
"COMPONENT" VARCHAR(255 CHAR) DEFAULT '',
"REDIRECT" VARCHAR(255 CHAR) DEFAULT '',
"ICON" VARCHAR(255 CHAR) DEFAULT '',
"IS_HIDDEN" BIT DEFAULT 0,
"IS_GENERAL" BIT DEFAULT 0,
"STATE" BIT DEFAULT 1 NOT NULL,
"SORT_VALUE" INT DEFAULT 1,
"SUB_GROUP" VARCHAR(255 CHAR) DEFAULT '',
"FIELD_IS_SECRET" BIT DEFAULT 0,
"FIELD_IS_EDIT" BIT DEFAULT 1,
"DATA_SCOPE" CHAR(2 CHAR),
"CUSTOM_CLASS" VARCHAR(255 CHAR),
"IS_DEF" BIT DEFAULT 0,
"TREE_PATH" VARCHAR(512 CHAR) DEFAULT '/',
"TREE_GRADE" INT DEFAULT 0,
"META_JSON" VARCHAR(512 CHAR) DEFAULT '{}',
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_RESOURCE_CODE" UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_RESOURCE IS '资源';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."APPLICATION_ID" IS '应用ID;#def_application';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."CODE" IS '编码;唯一编码，用于区分资源';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."COMPONENT" IS '页面路径;用于resource_type=菜单和视图. 前端页面在src/views目录下的相对地址.';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."CREATED_BY" IS '创建人id';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."CUSTOM_CLASS" IS '实现类;自定义实现类全类名';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."DATA_SCOPE" IS '数据范围;[01-全部 02-本单位及子级 03-本单位 04-本部门及子级 05-本部门 06-个人 07-自定义]';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."DESCRIBE_" IS '描述;resource_type=接口时表示接口说明';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."FIELD_IS_EDIT" IS '是否可以编辑;是否可以编辑(用于resource_type=字段)';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."FIELD_IS_SECRET" IS '是否脱敏;显示时是否需要脱敏实现 (用于resource_type=字段)';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."ICON" IS '图标';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."IS_DEF" IS '是否默认';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."IS_GENERAL" IS '是否公共资源;1-无需分配所有人就可以访问的';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."IS_HIDDEN" IS '是否隐藏菜单;
resource_type=20时生效';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."META_JSON" IS '元数据;菜单视图的元数据';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."NAME" IS '名称';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."OPEN_WITH" IS '打开方式;[01-组件 02-内链 03-外链]
@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.System.RESOURCE_OPEN_WITH)';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."PARENT_ID" IS '父级ID';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."PATH" IS '地址栏路径;用于resource_type=菜单和视图和接口.resource_type=菜单和视图，表示地址栏地址, http开头表示外链, is_frame_src 为true表示在框架类打开.resource_type=接口，表示后端接口请求地址.';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."REDIRECT" IS '重定向;用于resource_type=菜单和视图';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."RESOURCE_TYPE" IS '类型;[20-菜单 40-按钮 50-字段 60-数据]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS,dictType = EchoDictType.System.RESOURCE_TYPE)菜单即左侧显示的菜单视图即隐藏的菜单(需要配置在路由中)和页面上点击后需要通过路由打开的页面功能即页面上的非视图的按钮字段即列表页或编辑页的字段接口即后台的访问接口';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."SORT_VALUE" IS '排序;默认升序';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."STATE" IS '状态;[0-禁用 1-启用]';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."SUB_GROUP" IS '分组';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."TREE_GRADE" IS '树层级';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."TREE_PATH" IS '树路径';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."UPDATED_BY" IS '更新人id';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE."UPDATED_TIME" IS '更新时间';


CREATE TABLE "LAMP_NONE"."DEF_RESOURCE_API"
(
"ID" BIGINT NOT NULL,
"RESOURCE_ID" BIGINT NOT NULL,
"CONTROLLER" VARCHAR(255 CHAR),
"SPRING_APPLICATION_NAME" VARCHAR(255 CHAR),
"REQUEST_METHOD" VARCHAR(255 CHAR) NOT NULL,
"NAME" VARCHAR(255 CHAR),
"URI" VARCHAR(255 CHAR) NOT NULL,
"IS_INPUT" BIT,
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_RESOURCE_API IS '资源接口';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE_API."CONTROLLER" IS '控制器类名';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE_API."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE_API."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE_API."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE_API."IS_INPUT" IS '是否手动录入';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE_API."NAME" IS '接口名;接口上的注释';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE_API."REQUEST_METHOD" IS '请求类型';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE_API."RESOURCE_ID" IS '资源ID';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE_API."SPRING_APPLICATION_NAME" IS '所属服务;取配置文件中 spring.application.name';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE_API."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE_API."UPDATED_TIME" IS '最后更新时间';
COMMENT ON COLUMN LAMP_NONE.DEF_RESOURCE_API."URI" IS '接口地址;lamp-cloud版：uri需要拼接上gateway中路径前缀lamp-boot版: uri需要不需要拼接前缀';


CREATE OR REPLACE  INDEX "LAMP_NONE"."IDX_RES_API_RESOURCE_ID" ON "LAMP_NONE"."DEF_RESOURCE_API"("RESOURCE_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "LAMP_NONE"."DEF_USER"
(
"ID" BIGINT NOT NULL,
"USERNAME" VARCHAR(255 CHAR) NOT NULL,
"NICK_NAME" VARCHAR(255 CHAR) NOT NULL,
"EMAIL" VARCHAR(255 CHAR),
"MOBILE" VARCHAR(11 CHAR),
"ID_CARD" VARCHAR(18 CHAR),
"WX_OPEN_ID" VARCHAR(255 CHAR),
"DD_OPEN_ID" VARCHAR(255 CHAR),
"READONLY" BIT DEFAULT 0 NOT NULL,
"NATION" CHAR(2 CHAR) DEFAULT '',
"EDUCATION" CHAR(2 CHAR) DEFAULT '',
"SEX" CHAR(1 CHAR) DEFAULT '1',
"STATE" BIT DEFAULT 1,
"WORK_DESCRIBE" VARCHAR(255 CHAR) DEFAULT '',
"PASSWORD_ERROR_LAST_TIME" TIMESTAMP(0),
"PASSWORD_ERROR_NUM" INT DEFAULT 0,
"PASSWORD_EXPIRE_TIME" TIMESTAMP(0),
"PASSWORD" VARCHAR(64 CHAR) DEFAULT '' NOT NULL,
"SALT" VARCHAR(20 CHAR) DEFAULT '' NOT NULL,
"LAST_LOGIN_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_USER_EMAIL" UNIQUE("EMAIL"),
CONSTRAINT "UK_USER_ID_CARD" UNIQUE("ID_CARD"),
CONSTRAINT "UK_USER_MOBILE" UNIQUE("MOBILE"),
CONSTRAINT "UK_USER_USERNAME" UNIQUE("USERNAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_USER IS '用户';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."CREATED_BY" IS '创建人id';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."DD_OPEN_ID" IS '钉钉OpenId';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."EDUCATION" IS '学历;[01-小学 02-中学 03-高中 04-专科 05-本科 06-硕士 07-博士 08-博士后 99-其他]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Global.EDUCATION)';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."EMAIL" IS '邮箱';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."ID_CARD" IS '身份证;15或18位';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."LAST_LOGIN_TIME" IS '最后登录时间';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."MOBILE" IS '手机;1开头11位纯数字';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."NATION" IS '民族;[01-汉族 99-其他]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Global.NATION)';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."NICK_NAME" IS '昵称';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."PASSWORD" IS '密码';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."PASSWORD_ERROR_LAST_TIME" IS '输错密码时间';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."PASSWORD_ERROR_NUM" IS '密码错误次数';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."PASSWORD_EXPIRE_TIME" IS '密码过期时间';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."READONLY" IS '内置;[0-否 1-是]';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."SALT" IS '密码盐';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."SEX" IS '性别;[1-男 2-女 3-未知]
@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Global.SEX)';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."STATE" IS '状态;[0-禁用 1-启用]';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."UPDATED_BY" IS '更新人id';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."UPDATED_TIME" IS '更新时间';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."USERNAME" IS '用户名;大小写数字下划线';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."WORK_DESCRIBE" IS '工作描述';
COMMENT ON COLUMN LAMP_NONE.DEF_USER."WX_OPEN_ID" IS '微信OpenId';


CREATE TABLE "LAMP_NONE"."DEF_USER_APPLICATION"
(
"ID" BIGINT NOT NULL,
"USER_ID" BIGINT NOT NULL,
"APPLICATION_ID" BIGINT NOT NULL,
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.DEF_USER_APPLICATION IS '用户的默认应用';
COMMENT ON COLUMN LAMP_NONE.DEF_USER_APPLICATION."APPLICATION_ID" IS '所属应用ID';
COMMENT ON COLUMN LAMP_NONE.DEF_USER_APPLICATION."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.DEF_USER_APPLICATION."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.DEF_USER_APPLICATION."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.DEF_USER_APPLICATION."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN LAMP_NONE.DEF_USER_APPLICATION."UPDATED_TIME" IS '最后更新时间';
COMMENT ON COLUMN LAMP_NONE.DEF_USER_APPLICATION."USER_ID" IS '所属用户ID';


CREATE TABLE "LAMP_NONE"."EXTEND_INTERFACE_LOG"
(
"ID" BIGINT NOT NULL,
"INTERFACE_ID" BIGINT NOT NULL,
"NAME" VARCHAR(255 CHAR) NOT NULL,
"SUCCESS_COUNT" INT DEFAULT 0,
"FAIL_COUNT" INT DEFAULT 0,
"LAST_EXEC_TIME" TIMESTAMP(0),
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_EIL_INTERFACE_ID" UNIQUE("INTERFACE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.EXTEND_INTERFACE_LOG IS '接口执行日志';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOG."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOG."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOG."FAIL_COUNT" IS '失败次数';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOG."INTERFACE_ID" IS '接口ID;
#extend_interface';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOG."LAST_EXEC_TIME" IS '最后执行时间';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOG."NAME" IS '接口名称';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOG."SUCCESS_COUNT" IS '成功次数';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOG."UPDATED_BY" IS '修改人';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOG."UPDATED_TIME" IS '修改时间';


CREATE TABLE "LAMP_NONE"."EXTEND_INTERFACE_LOGGING"
(
"ID" BIGINT NOT NULL,
"LOG_ID" BIGINT NOT NULL,
"EXEC_TIME" TIMESTAMP(0) NOT NULL,
"STATUS" CHAR(2 CHAR) DEFAULT '01',
"PARAMS" CLOB,
"RESULT" CLOB,
"ERROR_MSG" CLOB,
"BIZ_ID" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.EXTEND_INTERFACE_LOGGING IS '接口执行日志记录';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOGGING."BIZ_ID" IS '业务ID';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOGGING."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOGGING."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOGGING."ERROR_MSG" IS '异常信息';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOGGING."EXEC_TIME" IS '执行时间';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOGGING."LOG_ID" IS '接口日志ID;
#extend_interface_log';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOGGING."PARAMS" IS '请求参数';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOGGING."RESULT" IS '接口返回';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOGGING."STATUS" IS '执行状态;[01-初始化 02-成功 03-失败]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.MSG_INTERFACE_LOGGING_STATUS)';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOGGING."UPDATED_BY" IS '修改人';
COMMENT ON COLUMN LAMP_NONE.EXTEND_INTERFACE_LOGGING."UPDATED_TIME" IS '修改时间';


CREATE TABLE "LAMP_NONE"."EXTEND_MSG"
(
"ID" BIGINT NOT NULL,
"TEMPLATE_CODE" VARCHAR(255 CHAR),
"TYPE" CHAR(2 CHAR),
"STATUS" VARCHAR(10 CHAR),
"CHANNEL" VARCHAR(255 CHAR),
"PARAM" TEXT,
"TITLE" VARCHAR(255 CHAR),
"CONTENT" CLOB,
"SEND_TIME" TIMESTAMP(0),
"BIZ_ID" BIGINT,
"BIZ_TYPE" VARCHAR(255 CHAR),
"REMIND_MODE" CHAR(2 CHAR),
"AUTHOR" VARCHAR(255 CHAR),
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.EXTEND_MSG IS '消息';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."AUTHOR" IS '发布人姓名';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."BIZ_ID" IS '业务ID';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."BIZ_TYPE" IS '业务类型';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."CHANNEL" IS '发送渠道;
#SourceType{APP:应用;SERVICE:服务}';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."CONTENT" IS '发送内容';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."CREATED_BY" IS '创建人ID';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."CREATED_ORG_ID" IS '创建人所属机构';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."ID" IS '短信记录ID';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."PARAM" IS '参数;需要封装为[{‘key’:‘‘,;’value’:‘‘}, {’key2’:‘‘, ’value2’:‘‘}]格式';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."REMIND_MODE" IS '提醒方式;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.NOTICE_REMIND_MODE)[01-待办 02-预警 03-提醒]';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."SEND_TIME" IS '发送时间';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."STATUS" IS '执行状态;
#TaskStatus{DRAFT:草稿;WAITING:等待执行;SUCCESS:执行成功;FAIL:执行失败}';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."TEMPLATE_CODE" IS '消息模板;
#extend_msg_template';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."TITLE" IS '标题';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."TYPE" IS '消息类型;[01-短信 02-邮件 03-站内信];@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.MSG_TEMPLATE_TYPE)';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."UPDATED_BY" IS '最后修改人';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG."UPDATED_TIME" IS '最后修改时间';


CREATE OR REPLACE  INDEX "LAMP_NONE"."TEMPATE_ID_TOPIC_CONTENT" ON "LAMP_NONE"."EXTEND_MSG"("TEMPLATE_CODE" ASC,"TITLE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "LAMP_NONE"."EXTEND_MSG_RECIPIENT"
(
"ID" BIGINT NOT NULL,
"MSG_ID" BIGINT NOT NULL,
"RECIPIENT" VARCHAR(255 CHAR) NOT NULL,
"EXT" VARCHAR(255 CHAR),
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.EXTEND_MSG_RECIPIENT IS '消息接收人';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG_RECIPIENT."CREATED_BY" IS '创建人';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG_RECIPIENT."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG_RECIPIENT."EXT" IS '扩展信息';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG_RECIPIENT."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG_RECIPIENT."MSG_ID" IS '任务ID;
#extend_msg';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG_RECIPIENT."RECIPIENT" IS '接收人;
可能是手机号、邮箱、用户ID等';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG_RECIPIENT."UPDATED_BY" IS '最后修改人';
COMMENT ON COLUMN LAMP_NONE.EXTEND_MSG_RECIPIENT."UPDATED_TIME" IS '最后修改时间';


CREATE OR REPLACE  INDEX "LAMP_NONE"."TASK_ID_TEL_NUM" ON "LAMP_NONE"."EXTEND_MSG_RECIPIENT"("MSG_ID" ASC,"RECIPIENT" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "LAMP_NONE"."EXTEND_NOTICE"
(
"ID" BIGINT NOT NULL,
"MSG_ID" BIGINT,
"BIZ_ID" VARCHAR(64 CHAR),
"BIZ_TYPE" VARCHAR(64 CHAR),
"RECIPIENT_ID" BIGINT NOT NULL,
"REMIND_MODE" CHAR(2 CHAR) NOT NULL,
"TITLE" VARCHAR(255 CHAR),
"CONTENT" CLOB,
"AUTHOR" VARCHAR(255 CHAR),
"URL" VARCHAR(255 CHAR),
"TARGET_" CHAR(2 CHAR),
"AUTO_READ" BIT,
"HANDLE_TIME" TIMESTAMP(0),
"READ_TIME" TIMESTAMP(0),
"IS_READ" BIT DEFAULT 0,
"IS_HANDLE" BIT DEFAULT 0,
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE LAMP_NONE.EXTEND_NOTICE IS '通知表';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."AUTHOR" IS '发布人';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."AUTO_READ" IS '自动已读';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."BIZ_ID" IS '业务ID';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."BIZ_TYPE" IS '业务类型';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."CONTENT" IS '内容';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."CREATED_BY" IS '创建人id';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."CREATED_ORG_ID" IS '所属组织';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."HANDLE_TIME" IS '处理时间';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."ID" IS 'ID';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."IS_HANDLE" IS '是否处理';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."IS_READ" IS '是否已读';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."MSG_ID" IS '消息ID';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."READ_TIME" IS '读取时间';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."RECIPIENT_ID" IS '接收人';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."REMIND_MODE" IS '提醒方式;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.NOTICE_REMIND_MODE)[01-待办 02-预警 03-提醒]';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."TARGET_" IS '打开方式;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.NOTICE_TARGET)[01-页面 02-弹窗 03-新开窗口]';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."TITLE" IS '标题';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."UPDATED_BY" IS '最后修改人';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."UPDATED_TIME" IS '最后修改时间';
COMMENT ON COLUMN LAMP_NONE.EXTEND_NOTICE."URL" IS '处理地址';


CREATE TABLE "LAMP_NONE"."UNDO_LOG"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"BRANCH_ID" BIGINT NOT NULL,
"XID" VARCHAR(100 CHAR) NOT NULL,
"CONTEXT" VARCHAR(128 CHAR) NOT NULL,
"ROLLBACK_INFO" BLOB NOT NULL,
"LOG_STATUS" INT NOT NULL,
"LOG_CREATED" TIMESTAMP(6) NOT NULL,
"LOG_MODIFIED" TIMESTAMP(6) NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UX_UNDO_LOG" UNIQUE("XID", "BRANCH_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 1;

COMMENT ON TABLE LAMP_NONE.UNDO_LOG IS 'AT transaction mode undo table';
COMMENT ON COLUMN LAMP_NONE.UNDO_LOG."BRANCH_ID" IS 'branch transaction id';
COMMENT ON COLUMN LAMP_NONE.UNDO_LOG."CONTEXT" IS 'undo_log context,such as serialization';
COMMENT ON COLUMN LAMP_NONE.UNDO_LOG."ID" IS 'increment id';
COMMENT ON COLUMN LAMP_NONE.UNDO_LOG."LOG_CREATED" IS 'create datetime';
COMMENT ON COLUMN LAMP_NONE.UNDO_LOG."LOG_MODIFIED" IS 'modify datetime';
COMMENT ON COLUMN LAMP_NONE.UNDO_LOG."LOG_STATUS" IS '0:normal status,1:defense status';
COMMENT ON COLUMN LAMP_NONE.UNDO_LOG."ROLLBACK_INFO" IS 'rollback info';
COMMENT ON COLUMN LAMP_NONE.UNDO_LOG."XID" IS 'global transaction id';


CREATE TABLE "LAMP_NONE"."WORKER_NODE"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"HOST_NAME" VARCHAR(64 CHAR) NOT NULL,
"PORT" VARCHAR(64 CHAR) NOT NULL,
"TYPE" INT NOT NULL,
"LAUNCH_DATE" DATE NOT NULL,
"MODIFIED" TIMESTAMP(0),
"CREATED" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 195;

COMMENT ON TABLE LAMP_NONE.WORKER_NODE IS 'DB;WorkerID Assigner for UID Generator';
COMMENT ON COLUMN LAMP_NONE.WORKER_NODE."CREATED" IS '创建时间';
COMMENT ON COLUMN LAMP_NONE.WORKER_NODE."HOST_NAME" IS '主机名';
COMMENT ON COLUMN LAMP_NONE.WORKER_NODE."ID" IS 'auto;increment id';
COMMENT ON COLUMN LAMP_NONE.WORKER_NODE."LAUNCH_DATE" IS '上线日期';
COMMENT ON COLUMN LAMP_NONE.WORKER_NODE."MODIFIED" IS '修改时间';
COMMENT ON COLUMN LAMP_NONE.WORKER_NODE."PORT" IS '端口';
COMMENT ON COLUMN LAMP_NONE.WORKER_NODE."TYPE" IS '节点类型:;ACTUAL 或者 CONTAINER';


